name: auto deploy to ssh

on:
  push:
    branches: [ master ]

jobs:
  build-to-deploy:
    name: build and deploy to server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 10
      - run: npm install
      - run: rm -fr ./build
      - run: npm run build --if-present
      - name: Deploy to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          first_ssh: |
            rm -fr /deploy
            mkdir -p /deploy
          scp: ./build/* => /deploy/
          last_ssh:
            ls -l /deploy
            /usr/sbin/nginx -s reload
