name: auto deploy to github page

on:
  push:
    branches: [ master ]

jobs:
  build-to-deploy:
    name: build and deploy to github page
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm install && npm run build
